# Generated by Django 6.0 on 2025-12-17 16:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(blank=True, help_text='Icon class or emoji', max_length=50)),
                ('category', models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('devops', 'DevOps'), ('mobile', 'Mobile'), ('database', 'Database'), ('other', 'Other')], default='other', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True, null=True)),
                ('bio', models.TextField(blank=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('github_url', models.URLField(blank=True, validators=[django.core.validators.URLValidator()])),
                ('x_url', models.URLField(blank=True, validators=[django.core.validators.URLValidator()])),
                ('portfolio_url', models.URLField(blank=True, validators=[django.core.validators.URLValidator()])),
                ('developer_type', models.CharField(choices=[('frontend', 'Frontend Developer'), ('backend', 'Backend Developer'), ('fullstack', 'Full Stack Developer'), ('devops', 'DevOps Engineer'), ('mobile', 'Mobile Developer'), ('data', 'Data Scientist'), ('ml', 'ML Engineer'), ('other', 'Other')], default='fullstack', max_length=20)),
                ('teammate_preference', models.CharField(choices=[('frontend', 'Frontend Developer'), ('backend', 'Backend Developer'), ('fullstack', 'Full Stack Developer'), ('devops', 'DevOps Engineer'), ('mobile', 'Mobile Developer'), ('data', 'Data Scientist'), ('ml', 'ML Engineer'), ('other', 'Other'), ('any', 'Any Developer')], default='any', max_length=20)),
                ('years_of_experience', models.IntegerField(default=0)),
                ('preferred_project_type', models.TextField(blank=True, help_text='e.g., SaaS, Mobile App, Web App, etc.')),
                ('availability', models.CharField(choices=[('part-time', 'Part-time'), ('full-time', 'Full-time'), ('weekends', 'Weekends only'), ('flexible', 'Flexible')], default='flexible', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('looking_for', models.ManyToManyField(blank=True, help_text="Skills you're looking for in a teammate", related_name='users_looking_for_skill', to='api.skill')),
                ('skills', models.ManyToManyField(blank=True, help_text='Skills and technologies you know', related_name='users_with_skill', to='api.skill')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MatchSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('suggested_users', models.ManyToManyField(related_name='suggested_to', to='api.userprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='api.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('compatibility_score', models.FloatField(default=0.0)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_user1', to='api.userprofile')),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_user2', to='api.userprofile')),
            ],
            options={
                'ordering': ['-compatibility_score', '-created_at'],
                'unique_together': {('user1', 'user2')},
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.match')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='api.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('liked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_received', to='api.userprofile')),
                ('liker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_given', to='api.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('liker', 'liked')},
            },
        ),
    ]
